# SPDX-FileCopyrightText: 2026 AcideFluorhydrique
# SPDX-License-Identifier: GPL-3.0-or-later
"""
省份與國家的唯一資料來源。

地圖檔（省界）與三份 strings.xml（譯名）都是從這張表產生的。
放在同一個檔案是刻意的：新增一座城市時只會改一個地方，
不會發生「地圖上有這個省、但翻譯漏了」的狀況。

PROVINCES 每一列：
    (鍵, 經度, 緯度, 城市等級, 國家代碼, English, 正體中文, 简体中文)

城市等級：0 = 無城、1 = 城鎮、2 = 城市、3 = 大城、4 = 核心城市。
"""

PROVINCES = [
    # ---- 西歐 ----
    ("prov_london",       -0.1,  51.5, 4, "GBR", "London",        "倫敦",     "伦敦"),
    ("prov_manchester",   -2.2,  53.5, 2, "GBR", "Manchester",    "曼徹斯特", "曼彻斯特"),
    ("prov_edinburgh",    -3.2,  55.9, 2, "GBR", "Edinburgh",     "愛丁堡",   "爱丁堡"),
    ("prov_dublin",       -6.3,  53.3, 2, "IRL", "Dublin",        "都柏林",   "都柏林"),
    ("prov_paris",         2.35, 48.9, 4, "FRA", "Paris",         "巴黎",     "巴黎"),
    ("prov_lyon",          4.8,  45.8, 2, "FRA", "Lyon",          "里昂",     "里昂"),
    ("prov_bordeaux",     -0.6,  44.8, 2, "FRA", "Bordeaux",      "波爾多",   "波尔多"),
    ("prov_brussels",      4.35, 50.85, 2, "BEL", "Brussels",     "布魯塞爾", "布鲁塞尔"),
    ("prov_amsterdam",     4.9,  52.4, 2, "NLD", "Amsterdam",     "阿姆斯特丹", "阿姆斯特丹"),
    ("prov_madrid",       -3.7,  40.4, 3, "ESP", "Madrid",        "馬德里",   "马德里"),
    ("prov_barcelona",     2.2,  41.4, 2, "ESP", "Barcelona",     "巴塞隆納", "巴塞罗那"),
    ("prov_seville",      -6.0,  37.4, 2, "ESP", "Seville",       "塞維利亞", "塞维利亚"),
    ("prov_lisbon",       -9.1,  38.7, 2, "PRT", "Lisbon",        "里斯本",   "里斯本"),
    ("prov_rome",         12.5,  41.9, 3, "ITA", "Rome",          "羅馬",     "罗马"),
    ("prov_milan",         9.2,  45.5, 3, "ITA", "Milan",         "米蘭",     "米兰"),
    ("prov_naples",       14.3,  40.8, 2, "ITA", "Naples",        "拿坡里",   "那不勒斯"),
    ("prov_zurich",        8.5,  47.4, 2, "CHE", "Zurich",        "蘇黎世",   "苏黎世"),

    # ---- 中歐與北歐 ----
    ("prov_berlin",       13.4,  52.5, 4, "DEU", "Berlin",        "柏林",     "柏林"),
    ("prov_hamburg",      10.0,  53.6, 2, "DEU", "Hamburg",       "漢堡",     "汉堡"),
    ("prov_munich",       11.6,  48.1, 3, "DEU", "Munich",        "慕尼黑",   "慕尼黑"),
    ("prov_cologne",       6.9,  50.9, 2, "DEU", "Cologne",       "科隆",     "科隆"),
    ("prov_vienna",       16.4,  48.2, 3, "AUT", "Vienna",        "維也納",   "维也纳"),
    ("prov_prague",       14.4,  50.1, 2, "CZE", "Prague",        "布拉格",   "布拉格"),
    ("prov_warsaw",       21.0,  52.2, 3, "POL", "Warsaw",        "華沙",     "华沙"),
    ("prov_krakow",       19.9,  50.1, 2, "POL", "Krakow",        "克拉科夫", "克拉科夫"),
    ("prov_budapest",     19.0,  47.5, 2, "HUN", "Budapest",      "布達佩斯", "布达佩斯"),
    ("prov_bucharest",    26.1,  44.4, 2, "ROU", "Bucharest",     "布加勒斯特", "布加勒斯特"),
    ("prov_belgrade",     20.5,  44.8, 2, "SRB", "Belgrade",      "貝爾格勒", "贝尔格莱德"),
    ("prov_sofia",        23.3,  42.7, 1, "BGR", "Sofia",         "索菲亞",   "索菲亚"),
    ("prov_athens",       23.7,  38.0, 2, "GRC", "Athens",        "雅典",     "雅典"),
    ("prov_stockholm",    18.1,  59.3, 2, "SWE", "Stockholm",     "斯德哥爾摩", "斯德哥尔摩"),
    ("prov_oslo",         10.7,  59.9, 2, "NOR", "Oslo",          "奧斯陸",   "奥斯陆"),
    ("prov_copenhagen",   12.6,  55.7, 2, "DNK", "Copenhagen",    "哥本哈根", "哥本哈根"),
    ("prov_helsinki",     25.0,  60.2, 2, "FIN", "Helsinki",      "赫爾辛基", "赫尔辛基"),
    ("prov_riga",         24.1,  56.9, 1, "LVA", "Riga",          "里加",     "里加"),
    ("prov_reykjavik",   -21.9,  64.1, 1, "ISL", "Reykjavik",     "雷克雅維克", "雷克雅未克"),
    ("prov_narvik",       17.4,  68.4, 1, "NOR", "Narvik",        "納爾維克", "纳尔维克"),

    # ---- 東歐與俄羅斯 ----
    ("prov_kyiv",         30.5,  50.5, 3, "UKR", "Kyiv",          "基輔",     "基辅"),
    ("prov_odesa",        30.7,  46.5, 2, "UKR", "Odesa",         "敖德薩",   "敖德萨"),
    ("prov_kharkiv",      36.2,  50.0, 2, "UKR", "Kharkiv",       "哈爾科夫", "哈尔科夫"),
    ("prov_minsk",        27.6,  53.9, 2, "BLR", "Minsk",         "明斯克",   "明斯克"),
    ("prov_moscow",       37.6,  55.8, 4, "RUS", "Moscow",        "莫斯科",   "莫斯科"),
    ("prov_petersburg",   30.3,  59.9, 3, "RUS", "St Petersburg", "聖彼得堡", "圣彼得堡"),
    ("prov_nizhny",       44.0,  56.3, 2, "RUS", "Nizhny Novgorod", "下諾夫哥羅德", "下诺夫哥罗德"),
    ("prov_kazan",        49.1,  55.8, 2, "RUS", "Kazan",         "喀山",     "喀山"),
    ("prov_volgograd",    44.5,  48.7, 2, "RUS", "Volgograd",     "伏爾加格勒", "伏尔加格勒"),
    ("prov_rostov",       39.7,  47.2, 2, "RUS", "Rostov",        "羅斯托夫", "罗斯托夫"),
    ("prov_yekaterinburg", 60.6, 56.8, 2, "RUS", "Yekaterinburg", "葉卡捷琳堡", "叶卡捷琳堡"),
    ("prov_murmansk",     33.1,  68.9, 1, "RUS", "Murmansk",      "莫曼斯克", "摩尔曼斯克"),
    ("prov_arkhangelsk",  40.5,  64.5, 1, "RUS", "Arkhangelsk",   "阿爾漢格爾", "阿尔汉格尔"),
    ("prov_omsk",         73.4,  55.0, 2, "RUS", "Omsk",          "鄂木斯克", "鄂木斯克"),
    ("prov_novosibirsk",  82.9,  55.0, 2, "RUS", "Novosibirsk",   "新西伯利亞", "新西伯利亚"),
    ("prov_krasnoyarsk",  92.9,  56.0, 2, "RUS", "Krasnoyarsk",   "克拉斯諾亞爾斯克", "克拉斯诺亚尔斯克"),
    ("prov_irkutsk",     104.3,  52.3, 1, "RUS", "Irkutsk",       "伊爾庫次克", "伊尔库茨克"),
    ("prov_yakutsk",     129.7,  62.0, 1, "RUS", "Yakutsk",       "雅庫次克", "雅库茨克"),
    ("prov_magadan",     150.8,  59.6, 1, "RUS", "Magadan",       "馬加丹",   "马加丹"),
    ("prov_norilsk",      88.2,  69.3, 1, "RUS", "Norilsk",       "諾里爾斯克", "诺里尔斯克"),
    ("prov_vladivostok", 131.9,  43.1, 2, "RUS", "Vladivostok",   "海參崴",   "海参崴"),
    ("prov_khabarovsk",  135.1,  48.5, 1, "RUS", "Khabarovsk",    "伯力",     "伯力"),
    ("prov_petropavlovsk", 158.6, 53.0, 1, "RUS", "Petropavlovsk", "彼得羅巴甫洛夫斯克", "彼得罗巴甫洛夫斯克"),

    # ---- 中亞與高加索 ----
    ("prov_astana",       71.4,  51.2, 2, "KAZ", "Astana",        "阿斯塔納", "阿斯塔纳"),
    ("prov_almaty",       76.9,  43.2, 2, "KAZ", "Almaty",        "阿拉木圖", "阿拉木图"),
    ("prov_aktobe",       57.2,  50.3, 1, "KAZ", "Aktobe",        "阿克托比", "阿克托别"),
    ("prov_tashkent",     69.3,  41.3, 2, "UZB", "Tashkent",      "塔什干",   "塔什干"),
    ("prov_ashgabat",     58.4,  37.9, 1, "TKM", "Ashgabat",      "阿什哈巴德", "阿什哈巴德"),
    ("prov_baku",         49.9,  40.4, 2, "AZE", "Baku",          "巴庫",     "巴库"),
    ("prov_tbilisi",      44.8,  41.7, 1, "GEO", "Tbilisi",       "第比利斯", "第比利斯"),
    ("prov_ulaanbaatar", 106.9,  47.9, 1, "MNG", "Ulaanbaatar",   "烏蘭巴托", "乌兰巴托"),

    # ---- 中東 ----
    ("prov_istanbul",     29.0,  41.0, 3, "TUR", "Istanbul",      "伊斯坦堡", "伊斯坦布尔"),
    ("prov_ankara",       32.9,  39.9, 2, "TUR", "Ankara",        "安卡拉",   "安卡拉"),
    ("prov_izmir",        27.1,  38.4, 2, "TUR", "Izmir",         "伊茲密爾", "伊兹密尔"),
    ("prov_tehran",       51.4,  35.7, 3, "IRN", "Tehran",        "德黑蘭",   "德黑兰"),
    ("prov_isfahan",      51.7,  32.7, 2, "IRN", "Isfahan",       "伊斯法罕", "伊斯法罕"),
    ("prov_tabriz",       46.3,  38.1, 1, "IRN", "Tabriz",        "大不里士", "大不里士"),
    ("prov_baghdad",      44.4,  33.3, 3, "IRQ", "Baghdad",       "巴格達",   "巴格达"),
    ("prov_basra",        47.8,  30.5, 2, "IRQ", "Basra",         "巴斯拉",   "巴士拉"),
    ("prov_damascus",     36.3,  33.5, 2, "SYR", "Damascus",      "大馬士革", "大马士革"),
    ("prov_jerusalem",    35.2,  31.8, 2, "ISR", "Jerusalem",     "耶路撒冷", "耶路撒冷"),
    ("prov_riyadh",       46.7,  24.7, 3, "SAU", "Riyadh",        "利雅德",   "利雅得"),
    ("prov_jeddah",       39.2,  21.5, 2, "SAU", "Jeddah",        "吉達",     "吉达"),
    ("prov_dubai",        55.3,  25.3, 2, "ARE", "Dubai",         "杜拜",     "迪拜"),
    ("prov_sanaa",        44.2,  15.4, 1, "YEM", "Sanaa",         "沙那",     "萨那"),
    ("prov_muscat",       58.4,  23.6, 1, "OMN", "Muscat",        "馬斯喀特", "马斯喀特"),
    ("prov_kabul",        69.2,  34.5, 2, "AFG", "Kabul",         "喀布爾",   "喀布尔"),

    # ---- 非洲 ----
    ("prov_cairo",        31.2,  30.0, 4, "EGY", "Cairo",         "開羅",     "开罗"),
    ("prov_alexandria",   29.9,  31.2, 2, "EGY", "Alexandria",    "亞歷山卓", "亚历山大"),
    ("prov_aswan",        32.9,  24.1, 1, "EGY", "Aswan",         "亞斯文",   "阿斯旺"),
    ("prov_tripoli",      13.2,  32.9, 2, "LBY", "Tripoli",       "的黎波里", "的黎波里"),
    ("prov_tunis",        10.2,  36.8, 2, "TUN", "Tunis",         "突尼斯",   "突尼斯"),
    ("prov_algiers",       3.0,  36.8, 2, "DZA", "Algiers",       "阿爾及爾", "阿尔及尔"),
    ("prov_tamanrasset",   5.5,  22.8, 1, "DZA", "Tamanrasset",   "塔曼拉塞特", "塔曼拉塞特"),
    ("prov_casablanca",   -7.6,  33.6, 2, "MAR", "Casablanca",    "卡薩布蘭卡", "卡萨布兰卡"),
    ("prov_dakar",       -17.4,  14.7, 2, "SEN", "Dakar",         "達卡",     "达喀尔"),
    ("prov_bamako",       -8.0,  12.6, 1, "MLI", "Bamako",        "巴馬科",   "巴马科"),
    ("prov_timbuktu",     -3.0,  16.8, 1, "MLI", "Timbuktu",      "廷巴克圖", "廷巴克图"),
    ("prov_abidjan",      -4.0,   5.3, 2, "CIV", "Abidjan",       "阿必尚",   "阿比让"),
    ("prov_accra",        -0.2,   5.6, 2, "GHA", "Accra",         "阿克拉",   "阿克拉"),
    ("prov_lagos",         3.4,   6.5, 3, "NGA", "Lagos",         "拉哥斯",   "拉各斯"),
    ("prov_kano",          8.5,  12.0, 2, "NGA", "Kano",          "卡諾",     "卡诺"),
    ("prov_ndjamena",     15.0,  12.1, 1, "TCD", "N'Djamena",     "恩將納",   "恩贾梅纳"),
    ("prov_khartoum",     32.5,  15.6, 2, "SDN", "Khartoum",      "喀土穆",   "喀土穆"),
    ("prov_addis",        38.7,   9.0, 2, "ETH", "Addis Ababa",   "阿迪斯阿貝巴", "亚的斯亚贝巴"),
    ("prov_mogadishu",    45.3,   2.0, 1, "SOM", "Mogadishu",     "摩加迪休", "摩加迪沙"),
    ("prov_nairobi",      36.8,  -1.3, 2, "KEN", "Nairobi",       "奈洛比",   "内罗毕"),
    ("prov_kampala",      32.6,   0.3, 1, "UGA", "Kampala",       "坎帕拉",   "坎帕拉"),
    ("prov_kinshasa",     15.3,  -4.3, 3, "COD", "Kinshasa",      "金夏沙",   "金沙萨"),
    ("prov_lubumbashi",   27.5, -11.7, 1, "COD", "Lubumbashi",    "盧本巴希", "卢本巴希"),
    ("prov_luanda",       13.2,  -8.8, 2, "AGO", "Luanda",        "羅安達",   "罗安达"),
    ("prov_dar_es_salaam", 39.3, -6.8, 2, "TZA", "Dar es Salaam", "三蘭港",   "达累斯萨拉姆"),
    ("prov_lusaka",       28.3, -15.4, 1, "ZMB", "Lusaka",        "路沙卡",   "卢萨卡"),
    ("prov_harare",       31.0, -17.8, 1, "ZWE", "Harare",        "哈拉雷",   "哈拉雷"),
    ("prov_windhoek",     17.1, -22.6, 1, "NAM", "Windhoek",      "溫荷克",   "温得和克"),
    ("prov_johannesburg", 28.0, -26.2, 3, "ZAF", "Johannesburg",  "約翰尼斯堡", "约翰内斯堡"),
    ("prov_cape_town",    18.4, -33.9, 2, "ZAF", "Cape Town",     "開普敦",   "开普敦"),
    ("prov_maputo",       32.6, -25.9, 1, "MOZ", "Maputo",        "馬普托",   "马普托"),
    ("prov_antananarivo", 47.5, -18.9, 1, "MDG", "Antananarivo",  "安塔那那利佛", "塔那那利佛"),

    # ---- 南亞 ----
    ("prov_delhi",        77.2,  28.6, 4, "IND", "Delhi",         "德里",     "德里"),
    ("prov_mumbai",       72.9,  19.1, 3, "IND", "Mumbai",        "孟買",     "孟买"),
    ("prov_kolkata",      88.4,  22.6, 3, "IND", "Kolkata",       "加爾各答", "加尔各答"),
    ("prov_chennai",      80.3,  13.1, 2, "IND", "Chennai",       "清奈",     "金奈"),
    ("prov_bangalore",    77.6,  13.0, 2, "IND", "Bengaluru",     "邦加羅爾", "班加罗尔"),
    ("prov_hyderabad",    78.5,  17.4, 2, "IND", "Hyderabad",     "海得拉巴", "海得拉巴"),
    ("prov_nagpur",       79.1,  21.1, 1, "IND", "Nagpur",        "那格浦爾", "那格浦尔"),
    ("prov_karachi",      67.0,  24.9, 3, "PAK", "Karachi",       "喀拉蚩",   "卡拉奇"),
    ("prov_lahore",       74.3,  31.5, 2, "PAK", "Lahore",        "拉合爾",   "拉合尔"),
    ("prov_dhaka",        90.4,  23.8, 2, "BGD", "Dhaka",         "達卡",     "达卡"),
    ("prov_colombo",      79.9,   6.9, 1, "LKA", "Colombo",       "可倫坡",   "科伦坡"),
    ("prov_kathmandu",    85.3,  27.7, 1, "NPL", "Kathmandu",     "加德滿都", "加德满都"),

    # ---- 東亞 ----
    ("prov_beijing",     116.4,  39.9, 4, "CHN", "Beijing",       "北京",     "北京"),
    ("prov_shanghai",    121.5,  31.2, 4, "CHN", "Shanghai",      "上海",     "上海"),
    ("prov_guangzhou",   113.3,  23.1, 3, "CHN", "Guangzhou",     "廣州",     "广州"),
    ("prov_wuhan",       114.3,  30.6, 3, "CHN", "Wuhan",         "武漢",     "武汉"),
    ("prov_chengdu",     104.1,  30.7, 3, "CHN", "Chengdu",       "成都",     "成都"),
    ("prov_chongqing",   106.5,  29.6, 2, "CHN", "Chongqing",     "重慶",     "重庆"),
    ("prov_xian",        108.9,  34.3, 2, "CHN", "Xi'an",         "西安",     "西安"),
    ("prov_shenyang",    123.4,  41.8, 2, "CHN", "Shenyang",      "瀋陽",     "沈阳"),
    ("prov_harbin",      126.6,  45.8, 2, "CHN", "Harbin",        "哈爾濱",   "哈尔滨"),
    ("prov_kunming",     102.7,  25.0, 2, "CHN", "Kunming",       "昆明",     "昆明"),
    ("prov_lanzhou",     103.8,  36.1, 1, "CHN", "Lanzhou",       "蘭州",     "兰州"),
    ("prov_urumqi",       87.6,  43.8, 1, "CHN", "Urumqi",        "烏魯木齊", "乌鲁木齐"),
    ("prov_lhasa",        91.1,  29.7, 1, "CHN", "Lhasa",         "拉薩",     "拉萨"),
    ("prov_hohhot",      111.7,  40.8, 1, "CHN", "Hohhot",        "呼和浩特", "呼和浩特"),
    ("prov_hong_kong",   114.2,  22.3, 3, "CHN", "Hong Kong",     "香港",     "香港"),
    ("prov_taipei",      121.5,  25.0, 3, "TWN", "Taipei",        "臺北",     "台北"),
    ("prov_kaohsiung",   120.3,  22.6, 2, "TWN", "Kaohsiung",     "高雄",     "高雄"),
    ("prov_seoul",       127.0,  37.6, 3, "KOR", "Seoul",         "首爾",     "首尔"),
    ("prov_busan",       129.1,  35.2, 2, "KOR", "Busan",         "釜山",     "釜山"),
    ("prov_pyongyang",   125.8,  39.0, 2, "PRK", "Pyongyang",     "平壤",     "平壤"),
    ("prov_tokyo",       139.7,  35.7, 4, "JPN", "Tokyo",         "東京",     "东京"),
    ("prov_osaka",       135.5,  34.7, 3, "JPN", "Osaka",         "大阪",     "大阪"),
    ("prov_fukuoka",     130.4,  33.6, 2, "JPN", "Fukuoka",       "福岡",     "福冈"),
    ("prov_sendai",      140.9,  38.3, 2, "JPN", "Sendai",        "仙台",     "仙台"),
    ("prov_sapporo",     141.4,  43.1, 2, "JPN", "Sapporo",       "札幌",     "札幌"),

    # ---- 東南亞 ----
    ("prov_yangon",       96.2,  16.8, 2, "MMR", "Yangon",        "仰光",     "仰光"),
    ("prov_mandalay",     96.1,  21.9, 1, "MMR", "Mandalay",      "曼德勒",   "曼德勒"),
    ("prov_bangkok",     100.5,  13.8, 3, "THA", "Bangkok",       "曼谷",     "曼谷"),
    ("prov_chiang_mai",   98.9,  18.8, 1, "THA", "Chiang Mai",    "清邁",     "清迈"),
    ("prov_hanoi",       105.9,  21.0, 2, "VNM", "Hanoi",         "河內",     "河内"),
    ("prov_ho_chi_minh", 106.7,  10.8, 3, "VNM", "Ho Chi Minh City", "胡志明市", "胡志明市"),
    ("prov_phnom_penh",  104.9,  11.6, 1, "KHM", "Phnom Penh",    "金邊",     "金边"),
    ("prov_kuala_lumpur", 101.7,  3.1, 2, "MYS", "Kuala Lumpur",  "吉隆坡",   "吉隆坡"),
    ("prov_kota_kinabalu", 116.1, 6.0, 1, "MYS", "Kota Kinabalu", "亞庇",     "亚庇"),
    ("prov_singapore",   103.8,   1.35, 3, "SGP", "Singapore",    "新加坡",   "新加坡"),
    ("prov_jakarta",     106.8,  -6.2, 3, "IDN", "Jakarta",       "雅加達",   "雅加达"),
    ("prov_surabaya",    112.7,  -7.3, 2, "IDN", "Surabaya",      "泗水",     "泗水"),
    ("prov_medan",        98.7,   3.6, 2, "IDN", "Medan",         "棉蘭",     "棉兰"),
    ("prov_banjarmasin", 114.6,  -3.3, 1, "IDN", "Banjarmasin",   "馬辰",     "马辰"),
    ("prov_makassar",    119.4,  -5.1, 1, "IDN", "Makassar",      "望加錫",   "望加锡"),
    ("prov_manila",      121.0,  14.6, 3, "PHL", "Manila",        "馬尼拉",   "马尼拉"),
    ("prov_cebu",        123.9,  10.3, 1, "PHL", "Cebu",          "宿霧",     "宿务"),
    ("prov_port_moresby", 147.2, -9.5, 1, "PNG", "Port Moresby",  "莫士比港", "莫尔兹比港"),

    # ---- 北美 ----
    ("prov_new_york",    -74.0,  40.7, 4, "USA", "New York",      "紐約",     "纽约"),
    ("prov_washington",  -77.0,  38.9, 3, "USA", "Washington",    "華盛頓",   "华盛顿"),
    ("prov_boston",      -71.1,  42.4, 2, "USA", "Boston",        "波士頓",   "波士顿"),
    ("prov_chicago",     -87.6,  41.9, 3, "USA", "Chicago",       "芝加哥",   "芝加哥"),
    ("prov_detroit",     -83.0,  42.3, 2, "USA", "Detroit",       "底特律",   "底特律"),
    ("prov_atlanta",     -84.4,  33.7, 2, "USA", "Atlanta",       "亞特蘭大", "亚特兰大"),
    ("prov_miami",       -80.2,  25.8, 2, "USA", "Miami",         "邁阿密",   "迈阿密"),
    ("prov_houston",     -95.4,  29.8, 3, "USA", "Houston",       "休士頓",   "休斯敦"),
    ("prov_dallas",      -96.8,  32.8, 2, "USA", "Dallas",        "達拉斯",   "达拉斯"),
    ("prov_minneapolis", -93.3,  45.0, 2, "USA", "Minneapolis",   "明尼阿波利斯", "明尼阿波利斯"),
    ("prov_denver",     -105.0,  39.7, 2, "USA", "Denver",        "丹佛",     "丹佛"),
    ("prov_phoenix",    -112.1,  33.4, 2, "USA", "Phoenix",       "鳳凰城",   "凤凰城"),
    ("prov_los_angeles", -118.2, 34.1, 4, "USA", "Los Angeles",   "洛杉磯",   "洛杉矶"),
    ("prov_san_francisco", -122.4, 37.8, 3, "USA", "San Francisco", "舊金山", "旧金山"),
    ("prov_seattle",    -122.3,  47.6, 2, "USA", "Seattle",       "西雅圖",   "西雅图"),
    ("prov_anchorage",  -149.9,  61.2, 1, "USA", "Anchorage",     "安克拉治", "安克雷奇"),
    ("prov_toronto",     -79.4,  43.7, 3, "CAN", "Toronto",       "多倫多",   "多伦多"),
    ("prov_montreal",    -73.6,  45.5, 2, "CAN", "Montreal",      "蒙特婁",   "蒙特利尔"),
    ("prov_vancouver",  -123.1,  49.3, 2, "CAN", "Vancouver",     "溫哥華",   "温哥华"),
    ("prov_calgary",    -114.1,  51.0, 2, "CAN", "Calgary",       "卡加利",   "卡尔加里"),
    ("prov_winnipeg",    -97.1,  49.9, 1, "CAN", "Winnipeg",      "溫尼伯",   "温尼伯"),
    ("prov_halifax",     -63.6,  44.6, 1, "CAN", "Halifax",       "哈利法克斯", "哈利法克斯"),
    ("prov_iqaluit",     -68.5,  63.7, 1, "CAN", "Iqaluit",       "伊魁特",   "伊卡卢伊特"),
    ("prov_yellowknife", -114.4, 62.5, 1, "CAN", "Yellowknife",   "黃刀鎮",   "黄刀镇"),
    ("prov_nuuk",        -51.7,  64.2, 1, "GRL", "Nuuk",          "努克",     "努克"),
    ("prov_mexico_city",  -99.1, 19.4, 4, "MEX", "Mexico City",   "墨西哥城", "墨西哥城"),
    ("prov_guadalajara", -103.3, 20.7, 2, "MEX", "Guadalajara",   "瓜達拉哈拉", "瓜达拉哈拉"),
    ("prov_monterrey",   -100.3, 25.7, 2, "MEX", "Monterrey",     "蒙特雷",   "蒙特雷"),
    ("prov_merida",       -89.6, 21.0, 1, "MEX", "Merida",        "梅里達",   "梅里达"),
    ("prov_guatemala",    -90.5, 14.6, 1, "GTM", "Guatemala City", "瓜地馬拉市", "危地马拉城"),
    ("prov_panama",       -79.5,  9.0, 2, "PAN", "Panama City",   "巴拿馬城", "巴拿马城"),
    ("prov_havana",       -82.4, 23.1, 2, "CUB", "Havana",        "哈瓦那",   "哈瓦那"),
    ("prov_santo_domingo", -69.9, 18.5, 1, "DOM", "Santo Domingo", "聖多明哥", "圣多明各"),

    # ---- 南美 ----
    ("prov_bogota",      -74.1,   4.7, 3, "COL", "Bogota",        "波哥大",   "波哥大"),
    ("prov_medellin",    -75.6,   6.3, 2, "COL", "Medellin",      "麥德林",   "麦德林"),
    ("prov_caracas",     -66.9,  10.5, 2, "VEN", "Caracas",       "卡拉卡斯", "加拉加斯"),
    ("prov_quito",       -78.5,  -0.2, 1, "ECU", "Quito",         "基多",     "基多"),
    ("prov_guayaquil",   -79.9,  -2.2, 1, "ECU", "Guayaquil",     "瓜亞基爾", "瓜亚基尔"),
    ("prov_lima",        -77.0, -12.0, 3, "PER", "Lima",          "利馬",     "利马"),
    ("prov_cusco",       -71.9, -13.5, 1, "PER", "Cusco",         "庫斯科",   "库斯科"),
    ("prov_la_paz",      -68.1, -16.5, 1, "BOL", "La Paz",        "拉巴斯",   "拉巴斯"),
    ("prov_santiago",    -70.7, -33.4, 3, "CHL", "Santiago",      "聖地牙哥", "圣地亚哥"),
    ("prov_antofagasta", -70.4, -23.6, 1, "CHL", "Antofagasta",   "安托法加斯塔", "安托法加斯塔"),
    ("prov_punta_arenas", -70.9, -53.2, 1, "CHL", "Punta Arenas", "蓬塔阿雷納斯", "蓬塔阿雷纳斯"),
    ("prov_buenos_aires", -58.4, -34.6, 4, "ARG", "Buenos Aires", "布宜諾斯艾利斯", "布宜诺斯艾利斯"),
    ("prov_cordoba_ar",  -64.2, -31.4, 2, "ARG", "Cordoba",       "科爾多瓦", "科尔多瓦"),
    ("prov_bariloche",   -71.3, -41.1, 1, "ARG", "Bariloche",     "巴里洛切", "巴里洛切"),
    ("prov_montevideo",  -56.2, -34.9, 1, "URY", "Montevideo",    "蒙特維多", "蒙得维的亚"),
    ("prov_asuncion",    -57.6, -25.3, 1, "PRY", "Asuncion",      "亞松森",   "亚松森"),
    ("prov_sao_paulo",   -46.6, -23.5, 4, "BRA", "Sao Paulo",     "聖保羅",   "圣保罗"),
    ("prov_rio",         -43.2, -22.9, 3, "BRA", "Rio de Janeiro", "里約熱內盧", "里约热内卢"),
    ("prov_brasilia",    -47.9, -15.8, 2, "BRA", "Brasilia",      "巴西利亞", "巴西利亚"),
    ("prov_salvador",    -38.5, -12.9, 2, "BRA", "Salvador",      "薩爾瓦多", "萨尔瓦多"),
    ("prov_recife",      -34.9,  -8.1, 2, "BRA", "Recife",        "累西腓",   "累西腓"),
    ("prov_manaus",      -60.0,  -3.1, 2, "BRA", "Manaus",        "瑪瑙斯",   "马瑙斯"),
    ("prov_belem",       -48.5,  -1.5, 1, "BRA", "Belem",         "貝倫",     "贝伦"),
    ("prov_porto_alegre", -51.2, -30.0, 2, "BRA", "Porto Alegre", "愉港",     "阿雷格里港"),

    # ---- 大洋洲 ----
    ("prov_sydney",      151.2, -33.9, 3, "AUS", "Sydney",        "雪梨",     "悉尼"),
    ("prov_melbourne",   145.0, -37.8, 3, "AUS", "Melbourne",     "墨爾本",   "墨尔本"),
    ("prov_brisbane",    153.0, -27.5, 2, "AUS", "Brisbane",      "布里斯本", "布里斯班"),
    ("prov_adelaide",    138.6, -34.9, 2, "AUS", "Adelaide",      "阿得雷德", "阿德莱德"),
    ("prov_perth",       115.9, -32.0, 2, "AUS", "Perth",         "伯斯",     "珀斯"),
    ("prov_darwin",      130.8, -12.5, 1, "AUS", "Darwin",        "達爾文",   "达尔文"),
    ("prov_alice_springs", 133.9, -23.7, 1, "AUS", "Alice Springs", "愛麗斯泉", "爱丽斯泉"),
    ("prov_hobart",      147.3, -42.9, 1, "AUS", "Hobart",        "荷巴特",   "霍巴特"),
    ("prov_auckland",    174.8, -36.9, 2, "NZL", "Auckland",      "奧克蘭",   "奥克兰"),
    ("prov_christchurch", 172.6, -43.5, 1, "NZL", "Christchurch",  "基督城",   "基督城"),
]


# 國家表：代碼 → (English, 正體, 简体, 顏色, AI 性格, 開局資金)
NATIONS = {
    "USA": ("United States",  "美利堅",     "美利坚",     "#4C7BA8", "BALANCED",    1600),
    "CAN": ("Canada",         "加拿大",     "加拿大",     "#6E93B5", "TURTLE",       700),
    "MEX": ("Mexico",         "墨西哥",     "墨西哥",     "#3F8F6B", "BALANCED",     600),
    "GTM": ("Guatemala",      "瓜地馬拉",   "危地马拉",   "#57A07E", "TURTLE",       220),
    "PAN": ("Panama",         "巴拿馬",     "巴拿马",     "#4E9E86", "TURTLE",       220),
    "CUB": ("Cuba",           "古巴",       "古巴",       "#A85C4C", "TURTLE",       260),
    "DOM": ("Dominicana",     "多明尼加",   "多米尼加",   "#9E6B58", "TURTLE",       200),
    "GRL": ("Greenland",      "格陵蘭",     "格陵兰",     "#8FA8B5", "TURTLE",       150),
    "BRA": ("Brazil",         "巴西",       "巴西",       "#4F9A50", "BALANCED",     900),
    "ARG": ("Argentina",      "阿根廷",     "阿根廷",     "#6FA8C4", "BALANCED",     600),
    "CHL": ("Chile",          "智利",       "智利",       "#A8544C", "TURTLE",       420),
    "PER": ("Peru",           "秘魯",       "秘鲁",       "#B06A4C", "BALANCED",     380),
    "COL": ("Colombia",       "哥倫比亞",   "哥伦比亚",   "#C29A3C", "BALANCED",     420),
    "VEN": ("Venezuela",      "委內瑞拉",   "委内瑞拉",   "#B4703C", "OPPORTUNIST",  380),
    "ECU": ("Ecuador",        "厄瓜多",     "厄瓜多尔",   "#C7A24E", "TURTLE",       240),
    "BOL": ("Bolivia",        "玻利維亞",   "玻利维亚",   "#8C9A4C", "TURTLE",       240),
    "PRY": ("Paraguay",       "巴拉圭",     "巴拉圭",     "#7F8F5C", "TURTLE",       200),
    "URY": ("Uruguay",        "烏拉圭",     "乌拉圭",     "#6E9BB0", "TURTLE",       220),
    "GBR": ("Britain",        "不列顛",     "不列颠",     "#8C4C4C", "BALANCED",    1100),
    "IRL": ("Ireland",        "愛爾蘭",     "爱尔兰",     "#4C8C5C", "TURTLE",       260),
    "FRA": ("France",         "法蘭西",     "法兰西",     "#4C5C9E", "BALANCED",     950),
    "ESP": ("Spain",          "西班牙",     "西班牙",     "#B08A3C", "BALANCED",     560),
    "PRT": ("Portugal",       "葡萄牙",     "葡萄牙",     "#4C8C7A", "TURTLE",       300),
    "BEL": ("Belgium",        "比利時",     "比利时",     "#9E8C4C", "TURTLE",       320),
    "NLD": ("Netherlands",    "尼德蘭",     "尼德兰",     "#C4813C", "TURTLE",       380),
    "DEU": ("Germany",        "德意志",     "德意志",     "#6E7A86", "AGGRESSIVE",  1150),
    "AUT": ("Austria",        "奧地利",     "奥地利",     "#A0A6AC", "TURTLE",       340),
    "CHE": ("Switzerland",    "瑞士",       "瑞士",       "#B45C5C", "TURTLE",       360),
    "ITA": ("Italy",          "義大利",     "意大利",     "#5C9E6E", "OPPORTUNIST",  700),
    "CZE": ("Czechia",        "捷克",       "捷克",       "#8A96A0", "TURTLE",       300),
    "POL": ("Poland",         "波蘭",       "波兰",       "#B4535C", "BALANCED",     520),
    "HUN": ("Hungary",        "匈牙利",     "匈牙利",     "#9E7A4C", "OPPORTUNIST",  300),
    "ROU": ("Romania",        "羅馬尼亞",   "罗马尼亚",   "#8C7A3C", "TURTLE",       320),
    "SRB": ("Serbia",         "塞爾維亞",   "塞尔维亚",   "#8C5C4C", "OPPORTUNIST",  260),
    "BGR": ("Bulgaria",       "保加利亞",   "保加利亚",   "#6E8C5C", "TURTLE",       240),
    "GRC": ("Greece",         "希臘",       "希腊",       "#4C7AA8", "TURTLE",       300),
    "SWE": ("Sweden",         "瑞典",       "瑞典",       "#4C6E9E", "TURTLE",       420),
    "NOR": ("Norway",         "挪威",       "挪威",       "#5C7EA8", "TURTLE",       380),
    "DNK": ("Denmark",        "丹麥",       "丹麦",       "#A85C6E", "TURTLE",       320),
    "FIN": ("Finland",        "芬蘭",       "芬兰",       "#7A9EB4", "TURTLE",       320),
    "LVA": ("Latvia",         "拉脫維亞",   "拉脱维亚",   "#8C6E7A", "TURTLE",       180),
    "ISL": ("Iceland",        "冰島",       "冰岛",       "#93A8B4", "TURTLE",       150),
    "UKR": ("Ukraine",        "烏克蘭",     "乌克兰",     "#C4A83C", "BALANCED",     620),
    "BLR": ("Belarus",        "白俄羅斯",   "白俄罗斯",   "#8C9A6E", "TURTLE",       280),
    "RUS": ("Russia",         "俄羅斯",     "俄罗斯",     "#8C6E4C", "AGGRESSIVE",  1500),
    "KAZ": ("Kazakhstan",     "哈薩克",     "哈萨克",     "#4C9E93", "BALANCED",     440),
    "UZB": ("Uzbekistan",     "烏茲別克",   "乌兹别克",   "#7AA88C", "TURTLE",       260),
    "TKM": ("Turkmenistan",   "土庫曼",     "土库曼",     "#A8956E", "TURTLE",       220),
    "AZE": ("Azerbaijan",     "亞塞拜然",   "阿塞拜疆",   "#6E9E4C", "TURTLE",       260),
    "GEO": ("Georgia",        "喬治亞",     "格鲁吉亚",   "#9EA8B4", "TURTLE",       200),
    "MNG": ("Mongolia",       "蒙古",       "蒙古",       "#B4A05C", "TURTLE",       240),
    "TUR": ("Turkey",         "土耳其",     "土耳其",     "#A84C4C", "AGGRESSIVE",   740),
    "IRN": ("Iran",           "伊朗",       "伊朗",       "#4C8C6E", "AGGRESSIVE",   700),
    "IRQ": ("Iraq",           "伊拉克",     "伊拉克",     "#8C8C4C", "OPPORTUNIST",  420),
    "SYR": ("Syria",          "敘利亞",     "叙利亚",     "#7A8C5C", "TURTLE",       260),
    "ISR": ("Israel",         "以色列",     "以色列",     "#5C86B4", "TURTLE",       420),
    "SAU": ("Saudi Arabia",   "沙烏地",     "沙特",       "#4C8C5C", "BALANCED",     820),
    "ARE": ("Emirates",       "阿聯",       "阿联酋",     "#6E9E7A", "TURTLE",       460),
    "YEM": ("Yemen",          "葉門",       "也门",       "#A87A5C", "TURTLE",       200),
    "OMN": ("Oman",           "阿曼",       "阿曼",       "#8C9E7A", "TURTLE",       260),
    "AFG": ("Afghanistan",    "阿富汗",     "阿富汗",     "#8C7A5C", "TURTLE",       220),
    "EGY": ("Egypt",          "埃及",       "埃及",       "#C4A84C", "BALANCED",     640),
    "LBY": ("Libya",          "利比亞",     "利比亚",     "#A89A5C", "TURTLE",       320),
    "TUN": ("Tunisia",        "突尼西亞",   "突尼斯",     "#9E5C5C", "TURTLE",       240),
    "DZA": ("Algeria",        "阿爾及利亞", "阿尔及利亚", "#5C9E5C", "BALANCED",     460),
    "MAR": ("Morocco",        "摩洛哥",     "摩洛哥",     "#A85C4C", "TURTLE",       380),
    "SEN": ("Senegal",        "塞內加爾",   "塞内加尔",   "#5C9E7A", "TURTLE",       220),
    "MLI": ("Mali",           "馬利",       "马里",       "#B49A5C", "TURTLE",       200),
    "CIV": ("Ivory Coast",    "象牙海岸",   "科特迪瓦",   "#C4954C", "TURTLE",       240),
    "GHA": ("Ghana",          "迦納",       "加纳",       "#B4844C", "TURTLE",       260),
    "NGA": ("Nigeria",        "奈及利亞",   "尼日利亚",   "#4C9E5C", "BALANCED",     560),
    "TCD": ("Chad",           "查德",       "乍得",       "#A8945C", "TURTLE",       180),
    "SDN": ("Sudan",          "蘇丹",       "苏丹",       "#9E8C4C", "TURTLE",       280),
    "ETH": ("Ethiopia",       "衣索比亞",   "埃塞俄比亚", "#6E9E4C", "BALANCED",     340),
    "SOM": ("Somalia",        "索馬利亞",   "索马里",     "#7AA8B4", "TURTLE",       180),
    "KEN": ("Kenya",          "肯亞",       "肯尼亚",     "#4C8C6E", "TURTLE",       320),
    "UGA": ("Uganda",         "烏干達",     "乌干达",     "#7A9E5C", "TURTLE",       220),
    "COD": ("Congo",          "剛果",       "刚果",       "#5C8C4C", "TURTLE",       380),
    "AGO": ("Angola",         "安哥拉",     "安哥拉",     "#A8804C", "TURTLE",       320),
    "TZA": ("Tanzania",       "坦尚尼亞",   "坦桑尼亚",   "#4C9E86", "TURTLE",       280),
    "ZMB": ("Zambia",         "尚比亞",     "赞比亚",     "#8C9E5C", "TURTLE",       220),
    "ZWE": ("Zimbabwe",       "辛巴威",     "津巴布韦",   "#9E8C5C", "TURTLE",       200),
    "NAM": ("Namibia",        "納米比亞",   "纳米比亚",   "#B4A06E", "TURTLE",       200),
    "ZAF": ("South Africa",   "南非",       "南非",       "#4C7A5C", "BALANCED",     640),
    "MOZ": ("Mozambique",     "莫三比克",   "莫桑比克",   "#7A9E6E", "TURTLE",       220),
    "MDG": ("Madagascar",     "馬達加斯加", "马达加斯加", "#8C6E9E", "TURTLE",       200),
    "IND": ("India",          "印度",       "印度",       "#C4864C", "BALANCED",    1150),
    "PAK": ("Pakistan",       "巴基斯坦",   "巴基斯坦",   "#4C8C5C", "AGGRESSIVE",   560),
    "BGD": ("Bangladesh",     "孟加拉",     "孟加拉",     "#5C9E7A", "TURTLE",       320),
    "LKA": ("Sri Lanka",      "斯里蘭卡",   "斯里兰卡",   "#B4844C", "TURTLE",       220),
    "NPL": ("Nepal",          "尼泊爾",     "尼泊尔",     "#A85C5C", "TURTLE",       180),
    "CHN": ("China",          "中國",       "中国",       "#B4454C", "BALANCED",    1700),
    "TWN": ("Taiwan",         "臺灣",       "台湾",       "#4C86B4", "TURTLE",       520),
    "KOR": ("Korea",          "韓國",       "韩国",       "#5C9EB4", "TURTLE",       620),
    "PRK": ("North Korea",    "北韓",       "朝鲜",       "#8C5C6E", "AGGRESSIVE",   360),
    "JPN": ("Japan",          "日本",       "日本",       "#C45C5C", "BALANCED",    1200),
    "MMR": ("Myanmar",        "緬甸",       "缅甸",       "#8C9E4C", "TURTLE",       300),
    "THA": ("Thailand",       "泰國",       "泰国",       "#5C86A8", "BALANCED",     480),
    "VNM": ("Vietnam",        "越南",       "越南",       "#B4954C", "BALANCED",     460),
    "KHM": ("Cambodia",       "柬埔寨",     "柬埔寨",     "#7A8C6E", "TURTLE",       200),
    "MYS": ("Malaysia",       "馬來西亞",   "马来西亚",   "#4C9E6E", "TURTLE",       420),
    "SGP": ("Singapore",      "新加坡",     "新加坡",     "#B45C5C", "TURTLE",       520),
    "IDN": ("Indonesia",      "印尼",       "印尼",       "#A85C4C", "BALANCED",     700),
    "PHL": ("Philippines",    "菲律賓",     "菲律宾",     "#4C86A8", "TURTLE",       420),
    "PNG": ("Papua",          "巴布亞",     "巴布亚",     "#7A9E86", "TURTLE",       180),
    "AUS": ("Australia",      "澳洲",       "澳大利亚",   "#C4A05C", "BALANCED",     820),
    "NZL": ("New Zealand",    "紐西蘭",     "新西兰",     "#5C9E93", "TURTLE",       380),
}


# 工業時代劇本：把現代國家併成幾個大勢力，同一張地圖直接變成另一種局。
# 這是「一張地圖多個劇本」的示範 —— 地形只讀一次，勢力分佈完全由劇本決定。
EMPIRE_MERGE = {
    "IRL": "GBR", "IND": "GBR", "PAK": "GBR", "BGD": "GBR", "LKA": "GBR",
    "MMR": "GBR", "MYS": "GBR", "SGP": "GBR", "NGA": "GBR", "GHA": "GBR",
    "KEN": "GBR", "UGA": "GBR", "TZA": "GBR", "ZMB": "GBR", "ZWE": "GBR",
    "ZAF": "GBR", "EGY": "GBR", "SDN": "GBR", "AUS": "GBR", "NZL": "GBR",
    "CAN": "GBR", "OMN": "GBR", "ARE": "GBR", "YEM": "GBR", "NPL": "GBR",
    "AFG": "GBR",
    "DZA": "FRA", "MAR": "FRA", "TUN": "FRA", "SEN": "FRA", "MLI": "FRA",
    "CIV": "FRA", "TCD": "FRA", "KHM": "FRA", "VNM": "FRA", "MDG": "FRA",
    "BEL": "FRA", "SYR": "FRA",
    "AUT": "AUT_HU", "CZE": "AUT_HU", "HUN": "AUT_HU", "SRB": "AUT_HU",
    "PNG": "DEU", "NAM": "DEU",
    "BLR": "RUS", "UKR": "RUS", "KAZ": "RUS", "UZB": "RUS", "TKM": "RUS",
    "AZE": "RUS", "GEO": "RUS", "FIN": "RUS", "LVA": "RUS", "POL": "RUS",
    "MNG": "RUS",
    "KOR": "JPN", "PRK": "JPN", "TWN": "JPN",
    "IDN": "NLD",
    "BGR": "TUR", "ROU": "TUR", "GRC": "TUR", "ISR": "TUR", "IRQ": "TUR",
    "SAU": "TUR",
    "LBY": "ITA", "SOM": "ITA", "ETH": "ITA",
    "AGO": "PRT", "MOZ": "PRT",
    "COD": "BEL_CONGO",
    "GTM": "MEX", "PAN": "USA", "CUB": "USA", "DOM": "USA", "PHL": "USA",
    "BOL": "PER", "PRY": "ARG", "URY": "ARG", "ECU": "COL", "VEN": "COL",
    "GRL": "DNK", "ISL": "DNK", "NOR": "SWE",
}

# 1939 年的世界。非洲與南亞在這一年幾乎沒有主權國家 —— 它們是英、法、
# 義、比、葡的屬地，所以那些省份直接算在宗主國名下。這不只是為了貼近史實：
# 把非洲攤成三十一個各擁一城的國家，等於在地圖上多放三十一個沒有戲份的
# 玩家，AI 要跑、顏色要分、玩家要認，換來的是零。
#
# 南美洲維持原樣。那裡確實是一堆各自獨立的小國，但它們全部中立，
# 不會有人被迫記住誰是誰 —— 中立的碎片不礙事，交戰的碎片才礙事。
WW2_MERGE = {
    # 大英帝國：自治領、印度、東南亞殖民地、非洲屬地、中東託管地。
    "CAN": "GBR", "AUS": "GBR", "NZL": "GBR", "ZAF": "GBR", "NAM": "GBR",
    "IND": "GBR", "PAK": "GBR", "BGD": "GBR", "LKA": "GBR", "NPL": "GBR",
    "MMR": "GBR", "MYS": "GBR", "SGP": "GBR",
    "EGY": "GBR", "SDN": "GBR", "KEN": "GBR", "UGA": "GBR", "TZA": "GBR",
    "NGA": "GBR", "GHA": "GBR", "ZMB": "GBR", "ZWE": "GBR",
    "ISR": "GBR", "IRQ": "GBR", "ARE": "GBR", "OMN": "GBR", "YEM": "GBR",

    # 法蘭西：北非、西非、印度支那、敘利亞託管地。
    "DZA": "FRA", "MAR": "FRA", "TUN": "FRA", "SEN": "FRA", "MLI": "FRA",
    "CIV": "FRA", "TCD": "FRA", "MDG": "FRA", "SYR": "FRA",
    "VNM": "FRA", "KHM": "FRA",

    # 義大利：利比亞、東非（衣索比亞 1936 年被占領）。
    "LBY": "ITA", "ETH": "ITA", "SOM": "ITA",

    # 其餘歐洲宗主國。
    "COD": "BEL",
    "AGO": "PRT", "MOZ": "PRT",
    "IDN": "NLD",
    "GRL": "DNK", "ISL": "DNK",
    "PNG": "GBR",  # 1939 年是澳洲代管地，不是 1914 年以前的德屬新幾內亞。

    # 美國：菲律賓與加勒比。
    "PHL": "USA", "CUB": "USA", "DOM": "USA", "PAN": "USA",

    # 日本：朝鮮與臺灣是併入的領土。
    "KOR": "JPN", "PRK": "JPN", "TWN": "JPN",

    # 蘇聯：加盟共和國與蒙古。
    "BLR": "RUS", "UKR": "RUS", "KAZ": "RUS", "UZB": "RUS", "TKM": "RUS",
    "AZE": "RUS", "GEO": "RUS", "LVA": "RUS", "MNG": "RUS",

    # 德國：1938 年的奧地利與 1939 年的捷克。
    "AUT": "DEU", "CZE": "DEU",
}


# 1939 年不參戰的國家。它們有城市、有守軍、也擋在路上，但 AI 走 TURTLE：
# 不主動宣戰，被打會還手。瑞士、瑞典、葡萄牙、西班牙、土耳其、愛爾蘭整場
# 中立；南美洲多數國家要到 1942 年之後才象徵性宣戰，在棋盤上等於不參戰。
WW2_NEUTRALS = {
    "CHE", "SWE", "PRT", "ESP", "IRL", "TUR", "IRN", "AFG", "SAU",
    "BRA", "ARG", "CHL", "COL", "PER", "VEN", "ECU", "BOL", "PRY", "URY",
    "GTM", "MEX",
}


# 合併後才出現的新勢力，需要自己的名字。
EXTRA_NATIONS = {
    "AUT_HU":    ("Danube Empire", "多瑙帝國", "多瑙帝国", "#A0A6AC", "OPPORTUNIST", 900),
    "BEL_CONGO": ("Congo Company", "剛果公司", "刚果公司", "#9E8C4C", "TURTLE",      400),
}


# 國旗。用區域指示符 emoji，交給系統字型畫 —— 零素材檔，
# 而且在沒有 emoji 字型的裝置上會自然退化成兩個字母（🇩🇪 → DE），仍然讀得出來。
# 併出來的歷史勢力沿用最接近的現代國旗。
FLAGS = {
    "AFG": "🇦🇫",
    "AGO": "🇦🇴",
    "ARE": "🇦🇪",
    "ARG": "🇦🇷",
    "AUS": "🇦🇺",
    "AUT": "🇦🇹",
    "AZE": "🇦🇿",
    "BEL": "🇧🇪",
    "BGD": "🇧🇩",
    "BGR": "🇧🇬",
    "BLR": "🇧🇾",
    "BOL": "🇧🇴",
    "BRA": "🇧🇷",
    "CAN": "🇨🇦",
    "CHE": "🇨🇭",
    "CHL": "🇨🇱",
    "CHN": "🇨🇳",
    "CIV": "🇨🇮",
    "COD": "🇨🇩",
    "COL": "🇨🇴",
    "CUB": "🇨🇺",
    "CZE": "🇨🇿",
    "DEU": "🇩🇪",
    "DNK": "🇩🇰",
    "DOM": "🇩🇴",
    "DZA": "🇩🇿",
    "ECU": "🇪🇨",
    "EGY": "🇪🇬",
    "ESP": "🇪🇸",
    "ETH": "🇪🇹",
    "FIN": "🇫🇮",
    "FRA": "🇫🇷",
    "GBR": "🇬🇧",
    "GEO": "🇬🇪",
    "GHA": "🇬🇭",
    "GRC": "🇬🇷",
    "GRL": "🇬🇱",
    "GTM": "🇬🇹",
    "HUN": "🇭🇺",
    "IDN": "🇮🇩",
    "IND": "🇮🇳",
    "IRL": "🇮🇪",
    "IRN": "🇮🇷",
    "IRQ": "🇮🇶",
    "ISL": "🇮🇸",
    "ISR": "🇮🇱",
    "ITA": "🇮🇹",
    "JPN": "🇯🇵",
    "KAZ": "🇰🇿",
    "KEN": "🇰🇪",
    "KHM": "🇰🇭",
    "KOR": "🇰🇷",
    "LBY": "🇱🇾",
    "LKA": "🇱🇰",
    "LVA": "🇱🇻",
    "MAR": "🇲🇦",
    "MDG": "🇲🇬",
    "MEX": "🇲🇽",
    "MLI": "🇲🇱",
    "MMR": "🇲🇲",
    "MNG": "🇲🇳",
    "MOZ": "🇲🇿",
    "MYS": "🇲🇾",
    "NAM": "🇳🇦",
    "NGA": "🇳🇬",
    "NLD": "🇳🇱",
    "NOR": "🇳🇴",
    "NPL": "🇳🇵",
    "NZL": "🇳🇿",
    "OMN": "🇴🇲",
    "PAK": "🇵🇰",
    "PAN": "🇵🇦",
    "PER": "🇵🇪",
    "PHL": "🇵🇭",
    "PNG": "🇵🇬",
    "POL": "🇵🇱",
    "PRK": "🇰🇵",
    "PRT": "🇵🇹",
    "PRY": "🇵🇾",
    "ROU": "🇷🇴",
    "RUS": "🇷🇺",
    "SAU": "🇸🇦",
    "SDN": "🇸🇩",
    "SEN": "🇸🇳",
    "SGP": "🇸🇬",
    "SOM": "🇸🇴",
    "SRB": "🇷🇸",
    "SWE": "🇸🇪",
    "SYR": "🇸🇾",
    "TCD": "🇹🇩",
    "THA": "🇹🇭",
    "TKM": "🇹🇲",
    "TUN": "🇹🇳",
    "TUR": "🇹🇷",
    "TWN": "🇹🇼",
    "TZA": "🇹🇿",
    "UGA": "🇺🇬",
    "UKR": "🇺🇦",
    "URY": "🇺🇾",
    "USA": "🇺🇸",
    "UZB": "🇺🇿",
    "VEN": "🇻🇪",
    "VNM": "🇻🇳",
    "YEM": "🇾🇪",
    "ZAF": "🇿🇦",
    "ZMB": "🇿🇲",
    "ZWE": "🇿🇼",
    # 帝國時代合併後才出現的勢力
    "AUT_HU": "🇦🇹",
    "BEL_CONGO": "🇧🇪",
    # 戰役演習陣營（之後會被年代劇本取代）
    "BLU": "🔵",
    "RED": "🔴",
    "GRN": "🟢",
}
